# https://github.com/probot/settings

branches:
    - name: master
      protection:
          enforce_admins: false
          required_pull_request_reviews:
              dismiss_stale_reviews: true
              require_code_owner_reviews: true
              required_approving_review_count: 1
          restrictions: null

labels:
    - name: bug
      color: ee0701

    - name: dependencies
      color: 0366d6

    - name: enhancement
      color: 0e8a16

    - name: question
      color: cc317c

    - name: security
      color: ee0701

    - name: stale
      color: eeeeee

repository:
    allow_merge_commit: true
    allow_rebase_merge: false
    allow_squash_merge: false
    default_branch: main
    description: "Session 'State of Nix at European Commission' for the Summer of Nix 2022"
    topics: session
    homepage: https://github.com/ecphp/session--nix-at-european-commission--summer-of-nix/releases/latest
    has_downloads: true
    has_issues: true
    has_pages: false
    has_projects: false
    has_wiki: false
    name: session--nix-at-european-commission--summer-of-nix
    private: true
